fastlane_version "1.105.0"

default_platform :ios

platform :ios do
    
  lane :tests do
    run_tests(workspace: "RhythmicRebellion.xcworkspace",
                 scheme: "RhythmicRebellion")
  end
    
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    ensure_git_status_clean
    
  end

  lane :beta do |options|

      ensure_git_branch(
                        branch: 'develop|hotfix'
                        )
      
    version_number = 0
    configuration = ""
    environmentName = ""
    
    ##parsing options
	if options[:patch]
        version_number = increment_version_number(bump_type: "patch")
    else
        version_number = increment_version_number(bump_type: "minor")
	end
    
    if options[:adhoc]
        configuration = "AdHoc"
        environmentName = "Dev"
    else
        configuration = "Release"
        environmentName = "Production"
    end

    ##building ipa
    gym(scheme: "RhythmicRebellion",
        configuration: configuration,
        include_bitcode: false,
        export_options: {
            method: "ad-hoc",
            provisioningProfiles: {
                "com.patronempowerment.rhytmicrebellion" => "RhythmicRebellion AdHoc"
            }
        }
    )
        
    ###uploading to crashlytics
    crashlytics(api_token: "a300d57f1f210d6200c91280eb4fe528696acb4d",
                build_secret: "87cc9027feb4d5479bb34e4346cf3c66bc13355724b999f294d3d9a89613169e",
                notes: changelog_from_git_commits,
                groups: "Basic")
    upload_symbols_to_crashlytics                    

    ##cleaning up
    File.delete("../RhythmicRebellion.ipa")
    File.delete("../RhythmicRebellion.app.dSYM.zip")
    
   resolve_link = "https://rhythmicrebellion.atlassian.net/browse/IOS-540?jql=project%20%3D%20IOS%20AND%20status%20%3D%20%22Test%20Ready%22%20AND%20%22Resolved%20in%20version%22%20%3D%20%22Build%20" + version_number.to_s + "%22"
   
    ##notifying testers
    slack( message: "New beta build is available. Check build details below or at your emails. \n\n*Please delete previous build from your device to avoid unexpected issues.*\n",
          
          use_webhook_configured_username_and_icon: true,
          payload: {
          'Version number' => get_version_number,
          'Environment' => environmentName,
          'Download Link' => "https://apps.crashlytics.com/projects",
          'Resolved Jira Issues' => "<" + resolve_link + "|click link>"
          },
          default_payloads: []
          )

          
    ###keeping record
    commit_version_bump(message: "Version bump to v#{version_number}")
    add_git_tag tag: version_number
    push_to_git_remote
    
  end

  lane :release do |options|
      
      ensure_git_branch(
                        branch: 'master'
                        )
                        
      ##building ipa
      gym(scheme: "RhythmicRebellion",
          configuration: "Release",
          export_method: "app-store",
          include_bitcode: true)

      upload_to_app_store(skip_screenshots: true,
                          skip_app_version_update: true,
                          skip_metadata: true)
                              
      ##cleaning up
      clean_build_artifacts
      
  end
  
  lane :refresh_dsym do |options|

    download_dsyms(version: "latest")
    upload_symbols_to_crashlytics(api_token: "a300d57f1f210d6200c91280eb4fe528696acb4d")
    clean_build_artifacts
     
  end

  after_all do
      
      ###notifying developer
      #notification(subtitle: "Finished lane", message: "Finished build lane succesfully")
      
  end
  
end
